const AWS_ACCESS_KEY = process.env.AWS_ACCESS_KEY;
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;
const AWS_BUCKET = process.env.AWS_BUCKET;

module.exports = { AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY, AWS_BUCKET };
